# Generated by Django 5.2.14 on 2026-06-03 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Friendly name for this connection', max_length=200)),
                ('connection_type', models.CharField(choices=[('postgresql', 'PostgreSQL'), ('mysql', 'MySQL'), ('csv', 'CSV File'), ('parquet', 'Parquet File')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('host', models.CharField(blank=True, max_length=500)),
                ('port', models.IntegerField(blank=True, null=True)),
                ('database_name', models.CharField(blank=True, max_length=200)),
                ('username', models.CharField(blank=True, max_length=200)),
                ('encrypted_password', models.BinaryField(blank=True, default=b'')),
                ('file', models.FileField(blank=True, upload_to='uploads/connections/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_tested', models.DateTimeField(blank=True, null=True)),
                ('last_test_success', models.BooleanField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Data Connection',
                'ordering': ['-created_at'],
            },
        ),
    ]
