# Generated by Django 5.2.14 on 2026-06-04 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0002_alter_dataconnection_connection_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataconnection',
            name='connection_type',
            field=models.CharField(choices=[('databricks', 'Databricks'), ('db2', 'DB2'), ('csv', 'Flat File CSV'), ('parquet', 'Flat File Parquet')], max_length=20),
        ),
    ]
