# Generated by Django 5.2.14 on 2026-06-04 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0003_alter_dataconnection_connection_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataconnection',
            name='connection_type',
            field=models.CharField(choices=[('postgresql', 'PostgreSQL'), ('mysql', 'MySQL'), ('databricks', 'Databricks'), ('db2', 'DB2'), ('flat_file', 'Flat File (CSV, Parquet)')], max_length=20),
        ),
    ]
