# Generated by Django 5.2.14 on 2026-06-06 08:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0006_alter_dataconnection_connection_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataconnection',
            name='description',
            field=models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(1000)]),
        ),
    ]
