# Generated by Django 5.2.14 on 2026-06-03 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mappings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('schedule_type', models.CharField(choices=[('manual', 'Manual Only'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('custom_cron', 'Custom Cron')], default='manual', max_length=20)),
                ('schedule_time', models.TimeField(blank=True, help_text='Time of day to run (for daily/weekly/monthly)', null=True)),
                ('schedule_day', models.IntegerField(blank=True, help_text='Day of week (0=Mon, 6=Sun) for weekly; Day of month for monthly', null=True)),
                ('cron_expression', models.CharField(blank=True, help_text='Custom cron expression (5 fields)', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('celery_task_name', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('next_run', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to=settings.AUTH_USER_MODEL)),
                ('mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='mappings.mapping')),
            ],
            options={
                'verbose_name': 'Workflow',
                'ordering': ['-created_at'],
            },
        ),
    ]
