# Generated by Django 5.2.14 on 2026-06-03 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mappings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('trigger_type', models.CharField(choices=[('manual', 'Manual'), ('scheduled', 'Scheduled')], default='manual', max_length=20)),
                ('progress', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('date_filter_start', models.DateField(blank=True, null=True)),
                ('date_filter_end', models.DateField(blank=True, null=True)),
                ('total_checks', models.IntegerField(default=0)),
                ('passed_checks', models.IntegerField(default=0)),
                ('failed_checks', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_runs', to='mappings.mapping')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Validation Run',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ValidationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(max_length=50)),
                ('source_value', models.TextField(blank=True, null=True)),
                ('target_value', models.TextField(blank=True, null=True)),
                ('is_match', models.BooleanField(default=False)),
                ('difference', models.TextField(blank=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('column_mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mappings.columnmapping')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='validations.validationrun')),
            ],
            options={
                'ordering': ['column_mapping', 'operation'],
            },
        ),
    ]
