# Generated by Django 5.2.14 on 2026-06-03 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='validationrun',
            name='selected_columns',
            field=models.TextField(blank=True, help_text='Comma-separated columns validated in this run.'),
        ),
    ]
