# Generated by Django 5.2.14 on 2026-06-05 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validations', '0002_validationrun_selected_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='validationrun',
            name='source_date_filter_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='validationrun',
            name='source_date_filter_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='validationrun',
            name='target_date_filter_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='validationrun',
            name='target_date_filter_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
