# Generated by Django 5.2.14 on 2026-06-08 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validations', '0003_validationrun_source_date_filter_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='validationrun',
            name='parameters',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
