# Generated by Django 5.2.14 on 2026-06-03 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('connections', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('source_schema', models.CharField(blank=True, max_length=200)),
                ('source_table', models.CharField(max_length=200)),
                ('target_schema', models.CharField(blank=True, max_length=200)),
                ('target_table', models.CharField(max_length=200)),
                ('date_filter_column', models.CharField(blank=True, max_length=200)),
                ('date_filter_type', models.CharField(choices=[('none', 'No Filter'), ('range', 'Date Range'), ('specific', 'Specific Date')], default='none', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to=settings.AUTH_USER_MODEL)),
                ('source_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_mappings', to='connections.dataconnection')),
                ('target_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_mappings', to='connections.dataconnection')),
            ],
            options={
                'verbose_name': 'Mapping',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ColumnMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_column', models.CharField(max_length=200)),
                ('source_datatype', models.CharField(blank=True, max_length=100)),
                ('target_column', models.CharField(max_length=200)),
                ('target_datatype', models.CharField(blank=True, max_length=100)),
                ('mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='column_mappings', to='mappings.mapping')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ValidationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('count', 'Count'), ('min', 'Minimum'), ('max', 'Maximum'), ('sum', 'Sum'), ('avg', 'Average'), ('distinct_count', 'Distinct Count'), ('null_check', 'Null Check'), ('duplicate_check', 'Duplicate Check'), ('data_type_check', 'Data Type Check'), ('row_count', 'Row Count Match')], max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('column_mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='mappings.columnmapping')),
            ],
            options={
                'ordering': ['operation'],
                'unique_together': {('column_mapping', 'operation')},
            },
        ),
    ]
