# Generated by Django 5.2.14 on 2026-06-03 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mappings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapping',
            name='date_filter_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mapping',
            name='date_filter_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
