# Generated by Django 5.2.14 on 2026-06-03 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mappings', '0002_mapping_date_filter_end_mapping_date_filter_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validationrule',
            name='operation',
            field=models.CharField(choices=[('count', 'Count'), ('min', 'Minimum'), ('max', 'Maximum'), ('sum', 'Sum'), ('distinct_count', 'Distinct Count'), ('null_check', 'Null Check'), ('duplicate_check', 'Duplicate Check'), ('data_type_check', 'Data Type Check'), ('row_count', 'Row Count Match')], max_length=30),
        ),
    ]
