# Generated by Django 5.2.14 on 2026-06-04 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mappings', '0003_alter_validationrule_operation'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapping',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
    ]
