# Generated by Django 5.2.14 on 2026-06-05 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mappings', '0004_mapping_is_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapping',
            name='source_date_column',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='mapping',
            name='source_date_filter_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mapping',
            name='source_date_filter_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mapping',
            name='source_date_filter_type',
            field=models.CharField(choices=[('none', 'No Filter'), ('range', 'Date Range'), ('specific', 'Specific Date')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='mapping',
            name='target_date_column',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='mapping',
            name='target_date_filter_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mapping',
            name='target_date_filter_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mapping',
            name='target_date_filter_type',
            field=models.CharField(choices=[('none', 'No Filter'), ('range', 'Date Range'), ('specific', 'Specific Date')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='validationrule',
            name='operation',
            field=models.CharField(choices=[('count', 'Count'), ('min', 'Minimum'), ('max', 'Maximum'), ('sum', 'Sum'), ('distinct_count', 'Distinct Count'), ('null_check', 'Null Check'), ('duplicate_check', 'Duplicate Check'), ('data_type_check', 'Data Type Check'), ('row_count', 'Row Count Match'), ('avg', 'Average'), ('length_sum_check', 'Length Sum Check'), ('regex_check', 'Regex Check'), ('unique_check', 'Unique Check'), ('range_check', 'Range Check'), ('min_date', 'Min Date'), ('max_date', 'Max Date')], max_length=30),
        ),
    ]
