# Generated by Django 5.2.14 on 2026-06-06 08:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mappings', '0005_mapping_source_date_column_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapping',
            name='description',
            field=models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(1000)]),
        ),
    ]
