# Generated by Django 5.2.14 on 2026-06-06 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mappings', '0006_alter_mapping_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapping',
            name='date_operator',
            field=models.CharField(default='=', max_length=5),
        ),
        migrations.AddField(
            model_name='mapping',
            name='date_relative_operator',
            field=models.CharField(default='+', max_length=5),
        ),
        migrations.AddField(
            model_name='mapping',
            name='date_relative_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mapping',
            name='date_value_type',
            field=models.CharField(default='calendar', max_length=20),
        ),
        migrations.AddField(
            model_name='mapping',
            name='source_date_operator',
            field=models.CharField(default='=', max_length=5),
        ),
        migrations.AddField(
            model_name='mapping',
            name='source_date_relative_operator',
            field=models.CharField(default='+', max_length=5),
        ),
        migrations.AddField(
            model_name='mapping',
            name='source_date_relative_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mapping',
            name='source_date_value_type',
            field=models.CharField(default='calendar', max_length=20),
        ),
        migrations.AddField(
            model_name='mapping',
            name='target_date_operator',
            field=models.CharField(default='=', max_length=5),
        ),
        migrations.AddField(
            model_name='mapping',
            name='target_date_relative_operator',
            field=models.CharField(default='+', max_length=5),
        ),
        migrations.AddField(
            model_name='mapping',
            name='target_date_relative_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mapping',
            name='target_date_value_type',
            field=models.CharField(default='calendar', max_length=20),
        ),
    ]
