# Generated by Django 5.2.14 on 2026-06-08 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mappings', '0008_remove_relative_date_fields_add_sum_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validationrule',
            name='operation',
            field=models.CharField(choices=[('count', 'Count'), ('min', 'Minimum'), ('max', 'Maximum'), ('sum', 'Sum'), ('distinct_count', 'Distinct Count'), ('null_check', 'Null Check'), ('duplicate_check', 'Duplicate Check'), ('data_type_check', 'Data Type Check'), ('row_count', 'Row Count Match'), ('avg', 'Average'), ('length_sum_check', 'Length Sum Check'), ('sum_length', 'Sum Length'), ('regex_check', 'Regex Check'), ('unique_check', 'Unique Check'), ('range_check', 'Range Check'), ('min_date', 'Min Date'), ('max_date', 'Max Date'), ('equals_check', 'Equals Check'), ('case_insensitive_check', 'Case Insensitive Check'), ('trim_check', 'Trim Check'), ('contains_check', 'Contains Check'), ('starts_with_check', 'Starts With Check'), ('ends_with_check', 'Ends With Check'), ('pattern_match', 'Pattern Match'), ('equals', 'Equals')], max_length=30),
        ),
    ]
